apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gmp-scraping
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: kube-train-pod
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gmp-system
      ports:
        - port: 8080
          protocol: TCP
