apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-train-chart.fullname" . }}-config
  labels:
    {{- include "kube-train-chart.labels" . | nindent 4 }}
data:
  TRAIN_MESSAGE: {{ .Values.config.trainMessage | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  GCP_PROJECT_ID: {{ .Values.config.gcpProjectId | quote }}
  LOGGING_STRUCTURED_FORMAT_CONSOLE: {{ .Values.config.loggingStructuredFormatConsole | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelExporterOtlpEndpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.config.otelExporterOtlpProtocol | quote }}
  OTEL_RESOURCE_ATTRIBUTES: {{ .Values.config.otelResourceAttributes | quote }}
  OTEL_METRICS_EXPORTER: {{ .Values.config.otelMetricsExporter | quote }}
  OTEL_LOGS_EXPORTER: {{ .Values.config.otelLogsExporter | quote }}
  JAVA_TOOL_OPTIONS: {{ .Values.config.javaTmpDir | quote }}
